#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import ts from 'typescript';
const a=process.argv.slice(2), root=path.resolve(a[0]); let docs=process.cwd(),out,json;
for(let i=1;i<a.length;i++){if(a[i]==='--docs')docs=path.resolve(a[++i]);else if(a[i]==='--out')out=path.resolve(a[++i]);else if(a[i]==='--json')json=path.resolve(a[++i]);}
const apiRoot=path.join(root,'src/bot/api'),abiFile=path.join(root,'src/bot/runtime/abi.ts'),runFile=path.join(root,'packages/rs2b0t-api/index.js'),dtsFile=path.join(root,'packages/rs2b0t-api/index.d.ts');
const walk=(d,p=()=>true)=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name),p):(p(path.join(d,e.name))?[path.join(d,e.name)]:[])).sort();
const sf=(f,k)=>ts.createSourceFile(f,fs.readFileSync(f,'utf8'),ts.ScriptTarget.Latest,true,k??(f.endsWith('.js')?ts.ScriptKind.JS:ts.ScriptKind.TS));
const mod=(n,k)=>!!n.modifiers?.some(x=>x.kind===k); const nm=n=>{const x=n.name;if(!x)return null;if(ts.isIdentifier(x)||ts.isStringLiteral(x)||ts.isNumericLiteral(x))return x.text;return x.getText()};
const vis=n=>mod(n,ts.SyntaxKind.PrivateKeyword)?'private':mod(n,ts.SyntaxKind.ProtectedKeyword)?'protected':'public';
const members=n=>n.members.map(m=>({name:ts.isConstructorDeclaration(m)?'constructor':nm(m),kind:ts.isMethodDeclaration(m)||ts.isMethodSignature(m)?'method':ts.isGetAccessorDeclaration(m)?'getter':ts.isSetAccessorDeclaration(m)?'setter':ts.isConstructorDeclaration(m)?'constructor':'property',visibility:vis(m),static:mod(m,ts.SyntaxKind.StaticKeyword)})).filter(x=>x.name);
function unwrap(e){if(!e)return null;if(ts.isObjectLiteralExpression(e))return e;if(ts.isParenthesizedExpression(e)||ts.isAsExpression(e)||ts.isTypeAssertionExpression(e))return unwrap(e.expression);if(ts.isCallExpression(e)&&e.arguments.length)return unwrap(e.arguments[0]);return null}
const objMembers=o=>o.properties.map(p=>ts.isSpreadAssignment(p)?{name:'...'+p.expression.getText(),kind:'spread',visibility:'public',static:false}:{name:nm(p),kind:ts.isMethodDeclaration(p)?'method':'property',visibility:'public',static:false}).filter(x=>x.name);
function api(){const files=walk(apiRoot,f=>f.endsWith('.ts')&&!f.endsWith('.d.ts')),symbols=[];for(const f of files){for(const s of sf(f).statements){if(!mod(s,ts.SyntaxKind.ExportKeyword))continue;const file=path.relative(root,f).replaceAll(path.sep,'/');if(ts.isVariableStatement(s))for(const d of s.declarationList.declarations){if(ts.isIdentifier(d.name)){const o=unwrap(d.initializer);symbols.push({name:d.name.text,kind:'const',file,members:o?objMembers(o):[]})}}else if(ts.isClassDeclaration(s)&&s.name)symbols.push({name:s.name.text,kind:'class',file,members:members(s)});else if(ts.isFunctionDeclaration(s)&&s.name)symbols.push({name:s.name.text,kind:'function',file,members:[]});}}return{files,symbols}}
function abi(){let found;function v(n){if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.name.text==='abi'){const o=unwrap(n.initializer);if(o)found=new Set(objMembers(o).filter(x=>!x.name.startsWith('...')).map(x=>x.name))}if(!found)ts.forEachChild(n,v)}v(sf(abiFile));return found}
function binds(n,o=[]){if(ts.isIdentifier(n))o.push(n.text);else if(ts.isObjectBindingPattern(n)||ts.isArrayBindingPattern(n))for(const e of n.elements)if(ts.isBindingElement(e))binds(e.name,o);return o}
function runtime(){const r=new Set;for(const s of sf(runFile,ts.ScriptKind.JS).statements){if(ts.isVariableStatement(s)&&mod(s,ts.SyntaxKind.ExportKeyword))for(const d of s.declarationList.declarations)for(const n of binds(d.name))r.add(n);else if(ts.isExportDeclaration(s)&&s.exportClause&&ts.isNamedExports(s.exportClause))for(const e of s.exportClause.elements)r.add(e.name.text)}return r}
function declarations(){const values=new Map,types=new Map;for(const s of sf(dtsFile).statements){if(!mod(s,ts.SyntaxKind.ExportKeyword))continue;if(ts.isInterfaceDeclaration(s))types.set(s.name.text,new Set(s.members.map(nm).filter(Boolean)));else if(ts.isTypeAliasDeclaration(s)&&ts.isTypeLiteralNode(s.type))types.set(s.name.text,new Set(s.type.members.map(nm).filter(Boolean)));else if(ts.isVariableStatement(s))for(const d of s.declarationList.declarations){if(!ts.isIdentifier(d.name))continue;let ms=new Set,ref;if(d.type&&ts.isTypeLiteralNode(d.type))ms=new Set(d.type.members.map(nm).filter(Boolean));else if(d.type&&ts.isTypeReferenceNode(d.type)&&ts.isIdentifier(d.type.typeName))ref=d.type.typeName.text;values.set(d.name.text,{members:ms,ref})}else if(ts.isClassDeclaration(s)&&s.name)values.set(s.name.text,{members:new Set(members(s).filter(x=>x.visibility==='public').map(x=>x.name))});else if(ts.isFunctionDeclaration(s)&&s.name)values.set(s.name.text,{members:new Set})}for(const v of values.values())if(v.ref&&types.has(v.ref))v.members=types.get(v.ref);return values}
const docset=walk(path.join(docs,'docs'),f=>f.endsWith('.md')).map(f=>({file:path.relative(docs,f).replaceAll(path.sep,'/'),text:fs.readFileSync(f,'utf8').toLowerCase()})); const hits=(s,m)=>docset.filter(d=>d.text.includes(s.toLowerCase())&&(!m||d.text.includes(m.toLowerCase()))).map(d=>d.file);
const A=api(),B=abi(),R=runtime(),D=declarations(); const cls=s=>R.has(s)?D.has(s)?'public':'runtime-drift':B.has(s)?'client-abi-only':'internal'; const mcls=(s,m,v)=>v!=='public'?'internal-member':!B.has(s)?'internal':!R.has(s)?'client-abi-only':!D.has(s)||!D.get(s).members.has(m)?'runtime-drift':'public';
const symbols=A.symbols.map(s=>({...s,classification:cls(s.name),inAbi:B.has(s.name),runtimeExported:R.has(s.name),declared:D.has(s.name),docs:hits(s.name),members:s.members.map(m=>({...m,classification:mcls(s.name,m.name,m.visibility),declared:D.get(s.name)?.members.has(m.name)??false,docs:hits(s.name,m.name)}))})), all=symbols.flatMap(s=>s.members.map(m=>({symbol:s.name,file:s.file,...m})));
const drift=all.filter(x=>x.classification==='runtime-drift'), rel=all.filter(x=>['public','runtime-drift','client-abi-only'].includes(x.classification)), bugs=[...D.keys()].filter(x=>!R.has(x)).sort(), counts={apiFiles:A.files.length,exportedSymbols:symbols.length,exportedMembers:all.length,publicSymbols:symbols.filter(x=>x.classification==='public').length,runtimeDriftSymbols:symbols.filter(x=>x.classification==='runtime-drift').length,abiOnlySymbolsInApiTree:symbols.filter(x=>x.classification==='client-abi-only').length,internalSymbols:symbols.filter(x=>x.classification==='internal').length,publicMembers:all.filter(x=>x.classification==='public').length,runtimeDriftMembers:drift.length,abiOnlyMembers:all.filter(x=>x.classification==='client-abi-only').length,undocumentedPublicOrDriftMembers:rel.filter(x=>!x.docs.length).length,declarationBugs:bugs.length};
const report={generatedAt:new Date().toISOString(),counts,abiOnly:[...B].filter(x=>!R.has(x)).sort(),runtimeNotDeclared:[...R].filter(x=>!D.has(x)).sort(),runtimeNotAbi:[...R].filter(x=>!B.has(x)).sort(),declarationBugs:bugs,symbols};
const lines=['# Automated rs2b2t API Symbol/Member Audit','',`Generated: ${report.generatedAt}`,'','## Counts','','| Metric | Count |','| --- | ---: |',...Object.entries(counts).map(([k,v])=>`| ${k} | ${v} |`),'','## Runtime/Declaration Drift Members','',...(drift.length?drift.map(x=>`- \`${x.symbol}.${x.name}\` — \`${x.file}\`${x.docs.length?' — docs: '+x.docs.join(', '):' — undocumented'}`):['None.']),'','## Undocumented Runtime/API-Relevant Members','',...rel.filter(x=>!x.docs.length).map(x=>`- \`${x.symbol}.${x.name}\` — ${x.classification} — \`${x.file}\``),'','## Boundary Mismatches','',`- ABI-only values: ${report.abiOnly.map(x=>'`'+x+'`').join(', ')||'none'}`,`- Runtime exports without declarations: ${report.runtimeNotDeclared.map(x=>'`'+x+'`').join(', ')||'none'}`,`- Runtime exports absent from ABI: ${report.runtimeNotAbi.map(x=>'`'+x+'`').join(', ')||'none'}`,`- Declared values not runtime-exported: ${bugs.map(x=>'`'+x+'`').join(', ')||'none'}`,'']; const md=lines.join('\n');
if(out){fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,md)}if(json){fs.mkdirSync(path.dirname(json),{recursive:true});fs.writeFileSync(json,JSON.stringify(report,null,2))}console.log(JSON.stringify(counts,null,2));
